available_text_models: ["gpt-4o","gpt-4o-mini"]

info:
  gpt-4o:
    type: chat_completion
    name: gpt-4o
    description: GPT-4 is the <b>smartest</b> and most advanced model in the world. This is the exact same model used in OpenAI's ChatGPT.

    price_per_1000_input_tokens: 0.0025
    price_per_1000_output_tokens: 0.01

    scores:
      Smart: 5
      Fast: 4
      Cheap: 3

  gpt-4o-mini:
    type: chat_completion
    name: gpt-4o-mini
    description: GPT-4o-mini is a special variant of GPT-40 designed for optimal performance and speed.

    price_per_1000_input_tokens: 0.00015
    price_per_1000_output_tokens: 0.0006

    scores:
      smart: 4
      fast: 5
      cheap: 5